# Generated by Django 4.0.4 on 2022-04-25 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boot', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inquiry',
            old_name='phone',
            new_name='phone_number',
        ),
    ]
